# Generated by Django 5.2.7 on 2025-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniStore', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved')], default='NONE', max_length=10),
        ),
    ]
