# Generated by Django 5.2.7 on 2025-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniStore', '0005_userprofile_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
