# Generated by Django 5.2.7 on 2025-11-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniStore', '0006_userprofile_shipping_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_postal_code',
        ),
    ]
