# Generated by Django 5.2.7 on 2025-11-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiniStore', '0007_remove_userprofile_shipping_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='seller_status',
            field=models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('CANCELLATION_REQUESTED', 'Cancellation Requested')], default='NONE', max_length=50),
        ),
    ]
